/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * MekanGo API specification
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  Business,
  BusinessAnalytics,
  BusinessCard,
  BusinessDetail,
  BusinessListResponse,
  Campaign,
  CampaignWithBusiness,
  Category,
  CreateBusinessBody,
  CreateCampaignBody,
  CreateProductBody,
  CreateReviewBody,
  FavoriteBody,
  HealthStatus,
  ListBusinessesParams,
  ListCampaignsParams,
  Product,
  RecordViewBody,
  Review,
  SubscribeBody,
  Subscription,
  SubscriptionPlan,
  UpdateBusinessBody,
  UpdateCampaignBody,
  UpdateProductBody,
} from "./api.schemas";

import { customFetch } from "../custom-fetch";
import type { ErrorType, BodyType } from "../custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List all categories
 */
export const getListCategoriesUrl = () => {
  return `/api/categories`;
};

export const listCategories = async (
  options?: RequestInit,
): Promise<Category[]> => {
  return customFetch<Category[]>(getListCategoriesUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListCategoriesQueryKey = () => {
  return [`/api/categories`] as const;
};

export const getListCategoriesQueryOptions = <
  TData = Awaited<ReturnType<typeof listCategories>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listCategories>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListCategoriesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listCategories>>> = ({
    signal,
  }) => listCategories({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listCategories>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListCategoriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listCategories>>
>;
export type ListCategoriesQueryError = ErrorType<unknown>;

/**
 * @summary List all categories
 */

export function useListCategories<
  TData = Awaited<ReturnType<typeof listCategories>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listCategories>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListCategoriesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List businesses with filters
 */
export const getListBusinessesUrl = (params?: ListBusinessesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/businesses?${stringifiedParams}`
    : `/api/businesses`;
};

export const listBusinesses = async (
  params?: ListBusinessesParams,
  options?: RequestInit,
): Promise<BusinessListResponse> => {
  return customFetch<BusinessListResponse>(getListBusinessesUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListBusinessesQueryKey = (params?: ListBusinessesParams) => {
  return [`/api/businesses`, ...(params ? [params] : [])] as const;
};

export const getListBusinessesQueryOptions = <
  TData = Awaited<ReturnType<typeof listBusinesses>>,
  TError = ErrorType<unknown>,
>(
  params?: ListBusinessesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listBusinesses>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListBusinessesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listBusinesses>>> = ({
    signal,
  }) => listBusinesses(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listBusinesses>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListBusinessesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listBusinesses>>
>;
export type ListBusinessesQueryError = ErrorType<unknown>;

/**
 * @summary List businesses with filters
 */

export function useListBusinesses<
  TData = Awaited<ReturnType<typeof listBusinesses>>,
  TError = ErrorType<unknown>,
>(
  params?: ListBusinessesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listBusinesses>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListBusinessesQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a new business profile
 */
export const getCreateBusinessUrl = () => {
  return `/api/businesses`;
};

export const createBusiness = async (
  createBusinessBody: CreateBusinessBody,
  options?: RequestInit,
): Promise<Business> => {
  return customFetch<Business>(getCreateBusinessUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createBusinessBody),
  });
};

export const getCreateBusinessMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createBusiness>>,
    TError,
    { data: BodyType<CreateBusinessBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createBusiness>>,
  TError,
  { data: BodyType<CreateBusinessBody> },
  TContext
> => {
  const mutationKey = ["createBusiness"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createBusiness>>,
    { data: BodyType<CreateBusinessBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createBusiness(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateBusinessMutationResult = NonNullable<
  Awaited<ReturnType<typeof createBusiness>>
>;
export type CreateBusinessMutationBody = BodyType<CreateBusinessBody>;
export type CreateBusinessMutationError = ErrorType<unknown>;

/**
 * @summary Create a new business profile
 */
export const useCreateBusiness = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createBusiness>>,
    TError,
    { data: BodyType<CreateBusinessBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createBusiness>>,
  TError,
  { data: BodyType<CreateBusinessBody> },
  TContext
> => {
  return useMutation(getCreateBusinessMutationOptions(options));
};

/**
 * @summary Get featured businesses for homepage
 */
export const getGetFeaturedBusinessesUrl = () => {
  return `/api/businesses/featured`;
};

export const getFeaturedBusinesses = async (
  options?: RequestInit,
): Promise<BusinessCard[]> => {
  return customFetch<BusinessCard[]>(getGetFeaturedBusinessesUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetFeaturedBusinessesQueryKey = () => {
  return [`/api/businesses/featured`] as const;
};

export const getGetFeaturedBusinessesQueryOptions = <
  TData = Awaited<ReturnType<typeof getFeaturedBusinesses>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getFeaturedBusinesses>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFeaturedBusinessesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFeaturedBusinesses>>
  > = ({ signal }) => getFeaturedBusinesses({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFeaturedBusinesses>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetFeaturedBusinessesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFeaturedBusinesses>>
>;
export type GetFeaturedBusinessesQueryError = ErrorType<unknown>;

/**
 * @summary Get featured businesses for homepage
 */

export function useGetFeaturedBusinesses<
  TData = Awaited<ReturnType<typeof getFeaturedBusinesses>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getFeaturedBusinesses>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetFeaturedBusinessesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get the authenticated user's business
 */
export const getGetMyBusinessUrl = () => {
  return `/api/businesses/my`;
};

export const getMyBusiness = async (
  options?: RequestInit,
): Promise<Business> => {
  return customFetch<Business>(getGetMyBusinessUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetMyBusinessQueryKey = () => {
  return [`/api/businesses/my`] as const;
};

export const getGetMyBusinessQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyBusiness>>,
  TError = ErrorType<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMyBusiness>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMyBusinessQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyBusiness>>> = ({
    signal,
  }) => getMyBusiness({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyBusiness>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMyBusinessQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyBusiness>>
>;
export type GetMyBusinessQueryError = ErrorType<void>;

/**
 * @summary Get the authenticated user's business
 */

export function useGetMyBusiness<
  TData = Awaited<ReturnType<typeof getMyBusiness>>,
  TError = ErrorType<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMyBusiness>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMyBusinessQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get business detail
 */
export const getGetBusinessUrl = (id: number) => {
  return `/api/businesses/${id}`;
};

export const getBusiness = async (
  id: number,
  options?: RequestInit,
): Promise<BusinessDetail> => {
  return customFetch<BusinessDetail>(getGetBusinessUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetBusinessQueryKey = (id: number) => {
  return [`/api/businesses/${id}`] as const;
};

export const getGetBusinessQueryOptions = <
  TData = Awaited<ReturnType<typeof getBusiness>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getBusiness>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBusinessQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getBusiness>>> = ({
    signal,
  }) => getBusiness(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getBusiness>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetBusinessQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBusiness>>
>;
export type GetBusinessQueryError = ErrorType<void>;

/**
 * @summary Get business detail
 */

export function useGetBusiness<
  TData = Awaited<ReturnType<typeof getBusiness>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getBusiness>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetBusinessQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update business profile
 */
export const getUpdateBusinessUrl = (id: number) => {
  return `/api/businesses/${id}`;
};

export const updateBusiness = async (
  id: number,
  updateBusinessBody: UpdateBusinessBody,
  options?: RequestInit,
): Promise<Business> => {
  return customFetch<Business>(getUpdateBusinessUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateBusinessBody),
  });
};

export const getUpdateBusinessMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateBusiness>>,
    TError,
    { id: number; data: BodyType<UpdateBusinessBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateBusiness>>,
  TError,
  { id: number; data: BodyType<UpdateBusinessBody> },
  TContext
> => {
  const mutationKey = ["updateBusiness"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateBusiness>>,
    { id: number; data: BodyType<UpdateBusinessBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateBusiness(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateBusinessMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateBusiness>>
>;
export type UpdateBusinessMutationBody = BodyType<UpdateBusinessBody>;
export type UpdateBusinessMutationError = ErrorType<unknown>;

/**
 * @summary Update business profile
 */
export const useUpdateBusiness = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateBusiness>>,
    TError,
    { id: number; data: BodyType<UpdateBusinessBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateBusiness>>,
  TError,
  { id: number; data: BodyType<UpdateBusinessBody> },
  TContext
> => {
  return useMutation(getUpdateBusinessMutationOptions(options));
};

/**
 * @summary Get campaigns for a business
 */
export const getGetBusinessCampaignsUrl = (id: number) => {
  return `/api/businesses/${id}/campaigns`;
};

export const getBusinessCampaigns = async (
  id: number,
  options?: RequestInit,
): Promise<Campaign[]> => {
  return customFetch<Campaign[]>(getGetBusinessCampaignsUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetBusinessCampaignsQueryKey = (id: number) => {
  return [`/api/businesses/${id}/campaigns`] as const;
};

export const getGetBusinessCampaignsQueryOptions = <
  TData = Awaited<ReturnType<typeof getBusinessCampaigns>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getBusinessCampaigns>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetBusinessCampaignsQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getBusinessCampaigns>>
  > = ({ signal }) => getBusinessCampaigns(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getBusinessCampaigns>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetBusinessCampaignsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBusinessCampaigns>>
>;
export type GetBusinessCampaignsQueryError = ErrorType<unknown>;

/**
 * @summary Get campaigns for a business
 */

export function useGetBusinessCampaigns<
  TData = Awaited<ReturnType<typeof getBusinessCampaigns>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getBusinessCampaigns>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetBusinessCampaignsQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get products/menu for a business
 */
export const getGetBusinessProductsUrl = (id: number) => {
  return `/api/businesses/${id}/products`;
};

export const getBusinessProducts = async (
  id: number,
  options?: RequestInit,
): Promise<Product[]> => {
  return customFetch<Product[]>(getGetBusinessProductsUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetBusinessProductsQueryKey = (id: number) => {
  return [`/api/businesses/${id}/products`] as const;
};

export const getGetBusinessProductsQueryOptions = <
  TData = Awaited<ReturnType<typeof getBusinessProducts>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getBusinessProducts>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBusinessProductsQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getBusinessProducts>>
  > = ({ signal }) => getBusinessProducts(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getBusinessProducts>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetBusinessProductsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBusinessProducts>>
>;
export type GetBusinessProductsQueryError = ErrorType<unknown>;

/**
 * @summary Get products/menu for a business
 */

export function useGetBusinessProducts<
  TData = Awaited<ReturnType<typeof getBusinessProducts>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getBusinessProducts>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetBusinessProductsQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get reviews for a business
 */
export const getGetBusinessReviewsUrl = (id: number) => {
  return `/api/businesses/${id}/reviews`;
};

export const getBusinessReviews = async (
  id: number,
  options?: RequestInit,
): Promise<Review[]> => {
  return customFetch<Review[]>(getGetBusinessReviewsUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetBusinessReviewsQueryKey = (id: number) => {
  return [`/api/businesses/${id}/reviews`] as const;
};

export const getGetBusinessReviewsQueryOptions = <
  TData = Awaited<ReturnType<typeof getBusinessReviews>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getBusinessReviews>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBusinessReviewsQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getBusinessReviews>>
  > = ({ signal }) => getBusinessReviews(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getBusinessReviews>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetBusinessReviewsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBusinessReviews>>
>;
export type GetBusinessReviewsQueryError = ErrorType<unknown>;

/**
 * @summary Get reviews for a business
 */

export function useGetBusinessReviews<
  TData = Awaited<ReturnType<typeof getBusinessReviews>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getBusinessReviews>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetBusinessReviewsQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a review for a business
 */
export const getCreateReviewUrl = (id: number) => {
  return `/api/businesses/${id}/reviews`;
};

export const createReview = async (
  id: number,
  createReviewBody: CreateReviewBody,
  options?: RequestInit,
): Promise<Review> => {
  return customFetch<Review>(getCreateReviewUrl(id), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createReviewBody),
  });
};

export const getCreateReviewMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createReview>>,
    TError,
    { id: number; data: BodyType<CreateReviewBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createReview>>,
  TError,
  { id: number; data: BodyType<CreateReviewBody> },
  TContext
> => {
  const mutationKey = ["createReview"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createReview>>,
    { id: number; data: BodyType<CreateReviewBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return createReview(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateReviewMutationResult = NonNullable<
  Awaited<ReturnType<typeof createReview>>
>;
export type CreateReviewMutationBody = BodyType<CreateReviewBody>;
export type CreateReviewMutationError = ErrorType<unknown>;

/**
 * @summary Create a review for a business
 */
export const useCreateReview = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createReview>>,
    TError,
    { id: number; data: BodyType<CreateReviewBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createReview>>,
  TError,
  { id: number; data: BodyType<CreateReviewBody> },
  TContext
> => {
  return useMutation(getCreateReviewMutationOptions(options));
};

/**
 * @summary List all active campaigns
 */
export const getListCampaignsUrl = (params?: ListCampaignsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/campaigns?${stringifiedParams}`
    : `/api/campaigns`;
};

export const listCampaigns = async (
  params?: ListCampaignsParams,
  options?: RequestInit,
): Promise<CampaignWithBusiness[]> => {
  return customFetch<CampaignWithBusiness[]>(getListCampaignsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListCampaignsQueryKey = (params?: ListCampaignsParams) => {
  return [`/api/campaigns`, ...(params ? [params] : [])] as const;
};

export const getListCampaignsQueryOptions = <
  TData = Awaited<ReturnType<typeof listCampaigns>>,
  TError = ErrorType<unknown>,
>(
  params?: ListCampaignsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listCampaigns>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListCampaignsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listCampaigns>>> = ({
    signal,
  }) => listCampaigns(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listCampaigns>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListCampaignsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listCampaigns>>
>;
export type ListCampaignsQueryError = ErrorType<unknown>;

/**
 * @summary List all active campaigns
 */

export function useListCampaigns<
  TData = Awaited<ReturnType<typeof listCampaigns>>,
  TError = ErrorType<unknown>,
>(
  params?: ListCampaignsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listCampaigns>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListCampaignsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List campaigns for authenticated user's business
 */
export const getListMyCampaignsUrl = () => {
  return `/api/my/campaigns`;
};

export const listMyCampaigns = async (
  options?: RequestInit,
): Promise<Campaign[]> => {
  return customFetch<Campaign[]>(getListMyCampaignsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListMyCampaignsQueryKey = () => {
  return [`/api/my/campaigns`] as const;
};

export const getListMyCampaignsQueryOptions = <
  TData = Awaited<ReturnType<typeof listMyCampaigns>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listMyCampaigns>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListMyCampaignsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listMyCampaigns>>> = ({
    signal,
  }) => listMyCampaigns({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listMyCampaigns>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListMyCampaignsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listMyCampaigns>>
>;
export type ListMyCampaignsQueryError = ErrorType<unknown>;

/**
 * @summary List campaigns for authenticated user's business
 */

export function useListMyCampaigns<
  TData = Awaited<ReturnType<typeof listMyCampaigns>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listMyCampaigns>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListMyCampaignsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a campaign
 */
export const getCreateCampaignUrl = () => {
  return `/api/my/campaigns`;
};

export const createCampaign = async (
  createCampaignBody: CreateCampaignBody,
  options?: RequestInit,
): Promise<Campaign> => {
  return customFetch<Campaign>(getCreateCampaignUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createCampaignBody),
  });
};

export const getCreateCampaignMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCampaign>>,
    TError,
    { data: BodyType<CreateCampaignBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCampaign>>,
  TError,
  { data: BodyType<CreateCampaignBody> },
  TContext
> => {
  const mutationKey = ["createCampaign"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCampaign>>,
    { data: BodyType<CreateCampaignBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createCampaign(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCampaignMutationResult = NonNullable<
  Awaited<ReturnType<typeof createCampaign>>
>;
export type CreateCampaignMutationBody = BodyType<CreateCampaignBody>;
export type CreateCampaignMutationError = ErrorType<unknown>;

/**
 * @summary Create a campaign
 */
export const useCreateCampaign = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCampaign>>,
    TError,
    { data: BodyType<CreateCampaignBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createCampaign>>,
  TError,
  { data: BodyType<CreateCampaignBody> },
  TContext
> => {
  return useMutation(getCreateCampaignMutationOptions(options));
};

/**
 * @summary Update a campaign
 */
export const getUpdateCampaignUrl = (id: number) => {
  return `/api/my/campaigns/${id}`;
};

export const updateCampaign = async (
  id: number,
  updateCampaignBody: UpdateCampaignBody,
  options?: RequestInit,
): Promise<Campaign> => {
  return customFetch<Campaign>(getUpdateCampaignUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateCampaignBody),
  });
};

export const getUpdateCampaignMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCampaign>>,
    TError,
    { id: number; data: BodyType<UpdateCampaignBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCampaign>>,
  TError,
  { id: number; data: BodyType<UpdateCampaignBody> },
  TContext
> => {
  const mutationKey = ["updateCampaign"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCampaign>>,
    { id: number; data: BodyType<UpdateCampaignBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateCampaign(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCampaignMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateCampaign>>
>;
export type UpdateCampaignMutationBody = BodyType<UpdateCampaignBody>;
export type UpdateCampaignMutationError = ErrorType<unknown>;

/**
 * @summary Update a campaign
 */
export const useUpdateCampaign = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCampaign>>,
    TError,
    { id: number; data: BodyType<UpdateCampaignBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateCampaign>>,
  TError,
  { id: number; data: BodyType<UpdateCampaignBody> },
  TContext
> => {
  return useMutation(getUpdateCampaignMutationOptions(options));
};

/**
 * @summary Delete a campaign
 */
export const getDeleteCampaignUrl = (id: number) => {
  return `/api/my/campaigns/${id}`;
};

export const deleteCampaign = async (
  id: number,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getDeleteCampaignUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteCampaignMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCampaign>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCampaign>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteCampaign"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCampaign>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteCampaign(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCampaignMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCampaign>>
>;

export type DeleteCampaignMutationError = ErrorType<unknown>;

/**
 * @summary Delete a campaign
 */
export const useDeleteCampaign = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCampaign>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteCampaign>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteCampaignMutationOptions(options));
};

/**
 * @summary List products for authenticated user's business
 */
export const getListMyProductsUrl = () => {
  return `/api/my/products`;
};

export const listMyProducts = async (
  options?: RequestInit,
): Promise<Product[]> => {
  return customFetch<Product[]>(getListMyProductsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListMyProductsQueryKey = () => {
  return [`/api/my/products`] as const;
};

export const getListMyProductsQueryOptions = <
  TData = Awaited<ReturnType<typeof listMyProducts>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listMyProducts>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListMyProductsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listMyProducts>>> = ({
    signal,
  }) => listMyProducts({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listMyProducts>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListMyProductsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listMyProducts>>
>;
export type ListMyProductsQueryError = ErrorType<unknown>;

/**
 * @summary List products for authenticated user's business
 */

export function useListMyProducts<
  TData = Awaited<ReturnType<typeof listMyProducts>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listMyProducts>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListMyProductsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a product
 */
export const getCreateProductUrl = () => {
  return `/api/my/products`;
};

export const createProduct = async (
  createProductBody: CreateProductBody,
  options?: RequestInit,
): Promise<Product> => {
  return customFetch<Product>(getCreateProductUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createProductBody),
  });
};

export const getCreateProductMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createProduct>>,
    TError,
    { data: BodyType<CreateProductBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createProduct>>,
  TError,
  { data: BodyType<CreateProductBody> },
  TContext
> => {
  const mutationKey = ["createProduct"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createProduct>>,
    { data: BodyType<CreateProductBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createProduct(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateProductMutationResult = NonNullable<
  Awaited<ReturnType<typeof createProduct>>
>;
export type CreateProductMutationBody = BodyType<CreateProductBody>;
export type CreateProductMutationError = ErrorType<unknown>;

/**
 * @summary Create a product
 */
export const useCreateProduct = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createProduct>>,
    TError,
    { data: BodyType<CreateProductBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createProduct>>,
  TError,
  { data: BodyType<CreateProductBody> },
  TContext
> => {
  return useMutation(getCreateProductMutationOptions(options));
};

/**
 * @summary Update a product
 */
export const getUpdateProductUrl = (id: number) => {
  return `/api/my/products/${id}`;
};

export const updateProduct = async (
  id: number,
  updateProductBody: UpdateProductBody,
  options?: RequestInit,
): Promise<Product> => {
  return customFetch<Product>(getUpdateProductUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateProductBody),
  });
};

export const getUpdateProductMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProduct>>,
    TError,
    { id: number; data: BodyType<UpdateProductBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateProduct>>,
  TError,
  { id: number; data: BodyType<UpdateProductBody> },
  TContext
> => {
  const mutationKey = ["updateProduct"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateProduct>>,
    { id: number; data: BodyType<UpdateProductBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateProduct(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateProductMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateProduct>>
>;
export type UpdateProductMutationBody = BodyType<UpdateProductBody>;
export type UpdateProductMutationError = ErrorType<unknown>;

/**
 * @summary Update a product
 */
export const useUpdateProduct = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProduct>>,
    TError,
    { id: number; data: BodyType<UpdateProductBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateProduct>>,
  TError,
  { id: number; data: BodyType<UpdateProductBody> },
  TContext
> => {
  return useMutation(getUpdateProductMutationOptions(options));
};

/**
 * @summary Delete a product
 */
export const getDeleteProductUrl = (id: number) => {
  return `/api/my/products/${id}`;
};

export const deleteProduct = async (
  id: number,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getDeleteProductUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteProductMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteProduct>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteProduct>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteProduct"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteProduct>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteProduct(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteProductMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteProduct>>
>;

export type DeleteProductMutationError = ErrorType<unknown>;

/**
 * @summary Delete a product
 */
export const useDeleteProduct = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteProduct>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteProduct>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteProductMutationOptions(options));
};

/**
 * @summary List user's favorite businesses
 */
export const getListFavoritesUrl = () => {
  return `/api/favorites`;
};

export const listFavorites = async (
  options?: RequestInit,
): Promise<BusinessCard[]> => {
  return customFetch<BusinessCard[]>(getListFavoritesUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListFavoritesQueryKey = () => {
  return [`/api/favorites`] as const;
};

export const getListFavoritesQueryOptions = <
  TData = Awaited<ReturnType<typeof listFavorites>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listFavorites>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListFavoritesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listFavorites>>> = ({
    signal,
  }) => listFavorites({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listFavorites>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListFavoritesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listFavorites>>
>;
export type ListFavoritesQueryError = ErrorType<unknown>;

/**
 * @summary List user's favorite businesses
 */

export function useListFavorites<
  TData = Awaited<ReturnType<typeof listFavorites>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listFavorites>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListFavoritesQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Add business to favorites
 */
export const getAddFavoriteUrl = () => {
  return `/api/favorites`;
};

export const addFavorite = async (
  favoriteBody: FavoriteBody,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getAddFavoriteUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(favoriteBody),
  });
};

export const getAddFavoriteMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addFavorite>>,
    TError,
    { data: BodyType<FavoriteBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addFavorite>>,
  TError,
  { data: BodyType<FavoriteBody> },
  TContext
> => {
  const mutationKey = ["addFavorite"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addFavorite>>,
    { data: BodyType<FavoriteBody> }
  > = (props) => {
    const { data } = props ?? {};

    return addFavorite(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddFavoriteMutationResult = NonNullable<
  Awaited<ReturnType<typeof addFavorite>>
>;
export type AddFavoriteMutationBody = BodyType<FavoriteBody>;
export type AddFavoriteMutationError = ErrorType<unknown>;

/**
 * @summary Add business to favorites
 */
export const useAddFavorite = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addFavorite>>,
    TError,
    { data: BodyType<FavoriteBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof addFavorite>>,
  TError,
  { data: BodyType<FavoriteBody> },
  TContext
> => {
  return useMutation(getAddFavoriteMutationOptions(options));
};

/**
 * @summary Remove business from favorites
 */
export const getRemoveFavoriteUrl = (businessId: number) => {
  return `/api/favorites/${businessId}`;
};

export const removeFavorite = async (
  businessId: number,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getRemoveFavoriteUrl(businessId), {
    ...options,
    method: "DELETE",
  });
};

export const getRemoveFavoriteMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeFavorite>>,
    TError,
    { businessId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeFavorite>>,
  TError,
  { businessId: number },
  TContext
> => {
  const mutationKey = ["removeFavorite"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeFavorite>>,
    { businessId: number }
  > = (props) => {
    const { businessId } = props ?? {};

    return removeFavorite(businessId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveFavoriteMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeFavorite>>
>;

export type RemoveFavoriteMutationError = ErrorType<unknown>;

/**
 * @summary Remove business from favorites
 */
export const useRemoveFavorite = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeFavorite>>,
    TError,
    { businessId: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof removeFavorite>>,
  TError,
  { businessId: number },
  TContext
> => {
  return useMutation(getRemoveFavoriteMutationOptions(options));
};

/**
 * @summary List available subscription plans
 */
export const getListSubscriptionPlansUrl = () => {
  return `/api/subscriptions/plans`;
};

export const listSubscriptionPlans = async (
  options?: RequestInit,
): Promise<SubscriptionPlan[]> => {
  return customFetch<SubscriptionPlan[]>(getListSubscriptionPlansUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListSubscriptionPlansQueryKey = () => {
  return [`/api/subscriptions/plans`] as const;
};

export const getListSubscriptionPlansQueryOptions = <
  TData = Awaited<ReturnType<typeof listSubscriptionPlans>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listSubscriptionPlans>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListSubscriptionPlansQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listSubscriptionPlans>>
  > = ({ signal }) => listSubscriptionPlans({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listSubscriptionPlans>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListSubscriptionPlansQueryResult = NonNullable<
  Awaited<ReturnType<typeof listSubscriptionPlans>>
>;
export type ListSubscriptionPlansQueryError = ErrorType<unknown>;

/**
 * @summary List available subscription plans
 */

export function useListSubscriptionPlans<
  TData = Awaited<ReturnType<typeof listSubscriptionPlans>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listSubscriptionPlans>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListSubscriptionPlansQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get authenticated user's current subscription
 */
export const getGetMySubscriptionUrl = () => {
  return `/api/subscriptions/my`;
};

export const getMySubscription = async (
  options?: RequestInit,
): Promise<Subscription> => {
  return customFetch<Subscription>(getGetMySubscriptionUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetMySubscriptionQueryKey = () => {
  return [`/api/subscriptions/my`] as const;
};

export const getGetMySubscriptionQueryOptions = <
  TData = Awaited<ReturnType<typeof getMySubscription>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMySubscription>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMySubscriptionQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMySubscription>>
  > = ({ signal }) => getMySubscription({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMySubscription>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMySubscriptionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMySubscription>>
>;
export type GetMySubscriptionQueryError = ErrorType<unknown>;

/**
 * @summary Get authenticated user's current subscription
 */

export function useGetMySubscription<
  TData = Awaited<ReturnType<typeof getMySubscription>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMySubscription>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMySubscriptionQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Subscribe to a plan
 */
export const getSubscribeUrl = () => {
  return `/api/subscriptions/subscribe`;
};

export const subscribe = async (
  subscribeBody: SubscribeBody,
  options?: RequestInit,
): Promise<Subscription> => {
  return customFetch<Subscription>(getSubscribeUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(subscribeBody),
  });
};

export const getSubscribeMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof subscribe>>,
    TError,
    { data: BodyType<SubscribeBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof subscribe>>,
  TError,
  { data: BodyType<SubscribeBody> },
  TContext
> => {
  const mutationKey = ["subscribe"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof subscribe>>,
    { data: BodyType<SubscribeBody> }
  > = (props) => {
    const { data } = props ?? {};

    return subscribe(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SubscribeMutationResult = NonNullable<
  Awaited<ReturnType<typeof subscribe>>
>;
export type SubscribeMutationBody = BodyType<SubscribeBody>;
export type SubscribeMutationError = ErrorType<unknown>;

/**
 * @summary Subscribe to a plan
 */
export const useSubscribe = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof subscribe>>,
    TError,
    { data: BodyType<SubscribeBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof subscribe>>,
  TError,
  { data: BodyType<SubscribeBody> },
  TContext
> => {
  return useMutation(getSubscribeMutationOptions(options));
};

/**
 * @summary Get analytics for authenticated user's business
 */
export const getGetMyAnalyticsUrl = () => {
  return `/api/analytics/my`;
};

export const getMyAnalytics = async (
  options?: RequestInit,
): Promise<BusinessAnalytics> => {
  return customFetch<BusinessAnalytics>(getGetMyAnalyticsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetMyAnalyticsQueryKey = () => {
  return [`/api/analytics/my`] as const;
};

export const getGetMyAnalyticsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyAnalytics>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMyAnalytics>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMyAnalyticsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyAnalytics>>> = ({
    signal,
  }) => getMyAnalytics({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyAnalytics>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMyAnalyticsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyAnalytics>>
>;
export type GetMyAnalyticsQueryError = ErrorType<unknown>;

/**
 * @summary Get analytics for authenticated user's business
 */

export function useGetMyAnalytics<
  TData = Awaited<ReturnType<typeof getMyAnalytics>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getMyAnalytics>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMyAnalyticsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Record a profile view for a business
 */
export const getRecordProfileViewUrl = () => {
  return `/api/analytics/my/record-view`;
};

export const recordProfileView = async (
  recordViewBody: RecordViewBody,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getRecordProfileViewUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(recordViewBody),
  });
};

export const getRecordProfileViewMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof recordProfileView>>,
    TError,
    { data: BodyType<RecordViewBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof recordProfileView>>,
  TError,
  { data: BodyType<RecordViewBody> },
  TContext
> => {
  const mutationKey = ["recordProfileView"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof recordProfileView>>,
    { data: BodyType<RecordViewBody> }
  > = (props) => {
    const { data } = props ?? {};

    return recordProfileView(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RecordProfileViewMutationResult = NonNullable<
  Awaited<ReturnType<typeof recordProfileView>>
>;
export type RecordProfileViewMutationBody = BodyType<RecordViewBody>;
export type RecordProfileViewMutationError = ErrorType<unknown>;

/**
 * @summary Record a profile view for a business
 */
export const useRecordProfileView = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof recordProfileView>>,
    TError,
    { data: BodyType<RecordViewBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof recordProfileView>>,
  TError,
  { data: BodyType<RecordViewBody> },
  TContext
> => {
  return useMutation(getRecordProfileViewMutationOptions(options));
};
