/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * MekanGo API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface Category {
  id: number;
  name: string;
  slug: string;
  icon: string;
  businessCount: number;
}

export interface BusinessCard {
  id: number;
  name: string;
  slug: string;
  categoryId: number;
  categoryName: string;
  city: string;
  coverImage?: string | null;
  logoImage?: string | null;
  rating: number;
  reviewCount: number;
  shortDescription?: string | null;
  hasActiveCampaign: boolean;
  activeCampaignDiscount?: number | null;
  subscriptionTier?: string | null;
}

export interface BusinessListResponse {
  businesses: BusinessCard[];
  total: number;
}

export type BusinessSocialLinks = { [key: string]: string } | null;

export interface Business {
  id: number;
  ownerId: string;
  name: string;
  slug: string;
  categoryId: number;
  description?: string | null;
  shortDescription?: string | null;
  address?: string | null;
  city: string;
  phone?: string | null;
  email?: string | null;
  website?: string | null;
  coverImage?: string | null;
  logoImage?: string | null;
  workingHours?: string | null;
  socialLinks?: BusinessSocialLinks;
  rating: number;
  reviewCount: number;
  createdAt: string;
}

export interface Campaign {
  id: number;
  businessId: number;
  title: string;
  description?: string | null;
  discountPercent: number;
  startDate: string;
  endDate: string;
  isActive: boolean;
  createdAt: string;
}

export type BusinessDetail = Business & {
  categoryName: string;
  activeCampaigns: Campaign[];
};

export type CreateBusinessBodySocialLinks = { [key: string]: string } | null;

export interface CreateBusinessBody {
  name: string;
  categoryId: number;
  description?: string | null;
  shortDescription?: string | null;
  address?: string | null;
  city: string;
  phone?: string | null;
  email?: string | null;
  website?: string | null;
  coverImage?: string | null;
  logoImage?: string | null;
  workingHours?: string | null;
  socialLinks?: CreateBusinessBodySocialLinks;
}

export type UpdateBusinessBodySocialLinks = { [key: string]: string } | null;

export interface UpdateBusinessBody {
  name?: string;
  categoryId?: number;
  description?: string | null;
  shortDescription?: string | null;
  address?: string | null;
  city?: string;
  phone?: string | null;
  email?: string | null;
  website?: string | null;
  coverImage?: string | null;
  logoImage?: string | null;
  workingHours?: string | null;
  socialLinks?: UpdateBusinessBodySocialLinks;
}

export type CampaignWithBusiness = Campaign & {
  businessName: string;
  businessCity: string;
  businessLogoImage?: string | null;
};

export interface CreateCampaignBody {
  title: string;
  description?: string | null;
  discountPercent: number;
  startDate: string;
  endDate: string;
}

export interface UpdateCampaignBody {
  title?: string;
  description?: string | null;
  discountPercent?: number;
  startDate?: string;
  endDate?: string;
}

export interface Product {
  id: number;
  businessId: number;
  name: string;
  description?: string | null;
  price: number;
  image?: string | null;
  createdAt: string;
}

export interface CreateProductBody {
  name: string;
  description?: string | null;
  price: number;
  image?: string | null;
}

export interface UpdateProductBody {
  name?: string;
  description?: string | null;
  price?: number;
  image?: string | null;
}

export interface Review {
  id: number;
  businessId: number;
  userId: string;
  userName: string;
  rating: number;
  comment?: string | null;
  createdAt: string;
}

export interface CreateReviewBody {
  /**
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  comment?: string | null;
}

export interface FavoriteBody {
  businessId: number;
}

export interface SubscriptionPlan {
  id: number;
  name: string;
  tier: string;
  priceMonthly: number;
  features: string[];
}

export interface Subscription {
  id: number;
  userId: string;
  planId: number;
  planName: string;
  tier: string;
  status: string;
  startDate: string;
  endDate?: string | null;
  createdAt: string;
}

export interface SubscribeBody {
  planId: number;
}

export interface DailyViewCount {
  date: string;
  count: number;
}

export interface BusinessAnalytics {
  totalProfileViews: number;
  viewsThisMonth: number;
  viewsLastMonth: number;
  totalCampaignClicks: number;
  totalReviews: number;
  averageRating: number;
  totalProducts: number;
  totalCampaigns: number;
  dailyViews: DailyViewCount[];
}

export interface RecordViewBody {
  businessId: number;
}

export type ListBusinessesParams = {
  categoryId?: number;
  city?: string;
  minRating?: number;
  hasActiveCampaign?: boolean;
  search?: string;
  limit?: number;
  offset?: number;
};

export type ListCampaignsParams = {
  limit?: number;
  offset?: number;
};
